### PR TITLE
Build conda environment during CI

### PR DESCRIPTION
**Pull request by frankharkins**
## Changes

Try building conda environment to avoid repeats of https://github.com/Qiskit/platypus-binder/pull/30.

I've set a timeout of 15 mins (for reference, the current environment takes ~7 mins to build).

### CODE REVIEW

**Comment by vabarbosa** [comment]
@frankharkins is this still needed after https://github.com/Qiskit/platypus-binder/pull/33?
just wanted to know if i should review or close :-)

**Comment by frankharkins** [comment]
This PR adds a github action that tests PRs by building the conda environment. The idea is to catch build errors before merging. Please take a look if you think it'll be useful.

**Comment by vabarbosa** [comment]
> This PR adds a github action that tests PRs by building the conda environment. The idea is to catch build errors before merging. Please take a look if you think it'll be useful.

oh ok.. thank you 👍🏽

**Review by vabarbosa — APPROVED** [review]
thank you 👍🏽

**Pull request merged**
